import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    schools: 'Schools',
    students: 'Students',
    teachers: 'Teachers',
    attendance: 'Attendance',
    assignments: 'Assignments',
    exams: 'Exams',
    results: 'Results',
    messages: 'Messages',
    announcements: 'Announcements',
    events: 'Events',
    timetable: 'Timetable',
    library: 'Library',
    analytics: 'Analytics',
    logout: 'Sign out',
    settings: 'Settings',
    quizzes: 'Quizzes',
    gradebook: 'Gradebook',
    meetings: 'Meetings',
    broadcast: 'Broadcast',
    behavior_log: 'Behavior Log',
    audit_trail: 'Audit Trail',
    course_builder: 'Course Builder',
    my_courses: 'My Courses',
    my_children: 'My Children',
    child_subjects: 'Subjects',
    child_attendance: 'Attendance',
    child_assignments: 'Assignments',
    child_exams: 'Exams',
    child_results: 'Results',
    child_fees: 'Fees & Payments',
    my_classes: 'My Classes',
    my_subjects: 'My Subjects',
    take_attendance: 'Take Attendance',
    submissions: 'Submissions',
    my_profile: 'My Profile',
    my_submissions: 'My Submissions',
    my_results: 'My Results',
    'fees_&_payments': 'Fees & Payments',
    viewing_child: 'Viewing child',
    live_data: 'Live school data',
    platform: 'Platform',
    billing: 'Billing',
    insights: 'Insights',
    system: 'System',
    overview: 'Overview',
    people: 'People',
    academics: 'Academics',
    teaching: 'Teaching',
    work: 'Work',
    communication: 'Communication',
    mobility: 'Mobility',
    my_learning: 'My Learning',
    my_school: 'My School',
    family: 'Family',
    school_service: 'School Service',
    welcome_back: 'Welcome back',
    next_actions: 'Your next best actions',
    school_pulse: 'School Pulse',
    demo_mode: 'DEMO MODE',
    language: 'Language',
    swahili: 'Swahili',
    english: 'English'
  },
  sw: {
    dashboard: 'Dashibodi',
    schools: 'Shule',
    students: 'Wanafunzi',
    teachers: 'Walimu',
    attendance: 'Mahudhurio',
    assignments: 'Kazi za Nyumbani',
    exams: 'Mitihani',
    results: 'Matokeo',
    messages: 'Ujumbe',
    announcements: 'Matangazo',
    events: 'Matukio',
    timetable: 'Ratiba',
    library: 'Maktaba',
    analytics: 'Uchambuzi',
    logout: 'Ondoka',
    settings: 'Mipangilio',
    quizzes: 'Maswali',
    gradebook: 'Kitabu cha Alama',
    meetings: 'Mikutano',
    broadcast: 'Tangazo la Wote',
    behavior_log: 'Logi ya Tabia',
    audit_trail: 'Kumbukumbu za Usalama',
    course_builder: 'Mjenzi wa Kozi',
    my_courses: 'Kozi Zangu',
    my_children: 'Watoto Wangu',
    child_subjects: 'Masomo',
    child_attendance: 'Mahudhurio',
    child_assignments: 'Kazi',
    child_exams: 'Mitihani',
    child_results: 'Matokeo',
    child_fees: 'Ada na Malipo',
    my_classes: 'Madarasa Yangu',
    my_subjects: 'Masomo Yangu',
    take_attendance: 'Chukua Mahudhurio',
    submissions: 'Zilizowasilishwa',
    my_profile: 'Wasifu Wangu',
    my_submissions: 'Kazi Nilizotuma',
    my_results: 'Matokeo Yangu',
    'fees_&_payments': 'Ada na Malipo',
    viewing_child: 'Kumtazama mtoto',
    live_data: 'Takwimu mubashara',
    platform: 'Mfumo',
    billing: 'Malipo',
    insights: 'Uchambuzi',
    system: 'Mfumo',
    overview: 'Maelezo ya Jumla',
    people: 'Watu',
    academics: 'Taaluma',
    teaching: 'Ufundishaji',
    work: 'Kazi',
    communication: 'Mawasiliano',
    mobility: 'Usafiri',
    my_learning: 'Masomo Yangu',
    my_school: 'Shule Yangu',
    family: 'Familia',
    school_service: 'Huduma za Shule',
    welcome_back: 'Karibu tena',
    next_actions: 'Hatua zako zijazo',
    school_pulse: 'Mapigo ya Shule',
    demo_mode: 'HALI YA MAJARIBIO',
    language: 'Lugha',
    swahili: 'Kiswahili',
    english: 'Kiingereza'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
