import React from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { AuthProvider } from './context/AuthContext'
import { LanguageProvider } from './context/LanguageContext'
import './styles/global.css'
import './styles/guide.css'
import './styles/modules.css'
import './styles/portals.css'
import './styles/blue-theme.css'
import './styles/landing-motion.css'
import './styles/background-animation.css'
import './styles/mobile.css'
import './styles/navigation.css'
import './styles/screenshot-layout.css'
import './styles/public-pages.css'
import './styles/dashboard-theme.css'
import './styles/super-admin.css'
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><AuthProvider><LanguageProvider><App /></LanguageProvider></AuthProvider></BrowserRouter></React.StrictMode>)
